language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
# PyPy versions
- "pypy2.7"
- "pypy3.5"
before_install:
- travis_retry pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
install:
- travis_retry pip install pytest codecov
script:
- pytest -v --cov=.
after_success:
  - codecov
sudo: false
